local options = {
  backup = false,
  clipboard = "unnamedplus",
  cmdheight = 2,
  completeopt = { "menuone", "noselect", "fuzzy" },
  conceallevel = 0,
  fileencoding = "utf-8",
  hlsearch = true,
  ignorecase = true,
  mouse = "a",
  pumheight = 10,
  showmode = false,
  showtabline = 1,
  smartcase = true,
  smartindent = true,
  splitbelow = true,
  splitright = true,
  swapfile = false,
  termguicolors = true,
  timeoutlen = 1000,
  undofile = true,
  updatetime = 300,
  writebackup = true,
  expandtab = true,
  shiftwidth = 2,
  tabstop = 2,
  smarttab = true,
  cursorline = true,
  number = true,
  relativenumber = true,
  numberwidth = 4,
  signcolumn = "yes",
  textwidth = 100,
  wrap = true,
  scrolloff = 8,
  guifont = "monospace:h17",
  shortmess = "ltToOcCF",
  whichwrap = "b,s,h,l,<,>,[,]"
}

for key, value in pairs(options) do 
  vim.opt[key] = value
end
